  
  datasource:    username: root
    password: saifulhaque7159
    url: jdbc:mysql://localhost:3306/rental
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/           