spring:
  datasource:
    url: jdbc:mysql://localhost:3306/catalogue
    username: root
    password: saifulhaque7159
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
management:
  endpoints:
    web:
      exposure:
        include: refresh