spring:
  cache:
    cache-names: UserCache
    ehcache:
      config: 'classpath:'
    type: ehcache

  datasource:
    url: jdbc:mysql://localhost:3306/user
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true  		
management:
  endpoints:
    web:
      exposure:
        include: refresh
        
        
 
logging:
   file:
       max-history: 7
       max-size: 10MB
       name: App.log
   level:
       com:
           dailycodebuffer: TRACE
   pattern:
       console: '%d [%level] %c{1.} [%t] %m%n'
       file: '%d [%level] %c{1.} [%t] %m%n'
management:
   endpoints:
       web:
           exposure:
               include: hystrix.stream


