spring:  datasource:    url: jdbc:mysql://localhost:3306/user
    username: root
    password: root
  jpa:    hibernate:      ddl-auto: update
eureka:  client:    serviceUrl:
      defaultZone: http://localhost:8761/eureka/              
                 